# Workflow for deploying an Angular app to GitHub Pages
name: Deploy Angular App to GitHub Pages

on:
  # Runs on pushes to the default branch
  push:
    branches: ["main"] # Change "main" to "master" if that's your default branch

  # Allows manual triggering from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Prevent multiple concurrent deployments
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Specify your Node.js version

      - name: Install dependencies
        run: npm install
      
      - name: Build Angular app
        run: npm run build -- --base-href "/sorting-steps/" # Adjust base-href for GitHub Pages
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/sorting-steps # Path to Angular build output

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
